version: "3"

# IPv4 only
# docker network create http_network

# IPv4/IPv6 network
# docker network create http_network --ipv6 --subnet "fd00:0000:0000:0000::/64"
# Refer to https://github.com/hardware/mailserver/#ipv6-support for more information.

networks:
  http_network:
    external: true
  mail_network:
    external: false

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    restart: ${RESTART_MODE}
    ports:
      - "80:80"
      - "443:443"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN2}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN3}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN4}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN5}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN6}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN7}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN8}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN9}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN10}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN11}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN12}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN13}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN14}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN15}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN16}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN17}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN18}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN19}
      #- traefik.frontend.rule=Host:mail.${MAILSERVER_DOMAIN20}
      - traefik.port=8080
      - traefik.docker.network=http_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOLUMES_ROOT_PATH}/traefik/traefik.toml:/traefik.toml:ro
      - ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/traefik/acme
    networks:
      - http_network

  mailserver:
    image: hardware/mailserver:${MAILSERVER_DOCKER_TAG}
    container_name: mailserver
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}                    # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: ${MAILSERVER_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN2}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN3}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN4}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN5}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN6}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN7}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN8}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN9}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN10}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN11}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN12}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN13}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN14}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN15}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN16}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN17}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN18}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN19}
      #- traefik.frontend.rule=Host:spam.${MAILSERVER_DOMAIN20}
      - traefik.port=11334
      - traefik.docker.network=http_network
    # extra_hosts:                          - Required for external database (on other server or for local databases on host without docker)
    #  - "mariadb:xx.xx.xx.xx"              - Replace with IP address of MariaDB server
    #  - "redis:xx.xx.xx.xx"                - Replace with IP address of Redis server
    ports:
      - "25:25"       # SMTP                - Required
    # - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
    # - "465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    # - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
    - DBDRIVER=pgsql
    - DBHOST=postgres
    - DBPORT=5432
    - DBPASS=${DATABASE_USER_PASSWORD}       # MariaDB database password (required)
    - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}     # Rspamd WebUI password (required)
    - OPENDKIM_KEY_LENGTH=${OPENDKIM_KEY_LENGTH}
    # - ADD_DOMAINS=aa.tld, www.bb.tld...      # Add additional domains separated by commas (needed for dkim keys etc.)
    # - DEBUG_MODE=true                        # Enable Postfix, Dovecot, Rspamd and Unbound verbose logging
    # - ENABLE_POP3=true                       # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true                  # Enable fetchmail forwarding
    # - DISABLE_RATELIMITING=false             # Enable ratelimiting policy
    # - DISABLE_CLAMAV=true                    # Disable virus scanning
    # - DISABLE_SIGNING=true                   # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true               # Disable greylisting policy
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - ${VOLUMES_ROOT_PATH}/mail:/var/mail
      - ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/letsencrypt/acme
    depends_on:
      - postgres
      - redis
      #- mariadb
    networks:
      - mail_network
      - http_network

  # Administration interface
  # https://github.com/hardware/postfixadmin
  # http://postfixadmin.sourceforge.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}
    hostname: ${MAILSERVER_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN2}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN3}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN4}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN5}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN6}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN7}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN8}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN9}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN10}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN11}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN12}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN13}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN14}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN15}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN16}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN17}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN18}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN19}
      #- traefik.frontend.rule=Host:postfixadmin.${MAILSERVER_DOMAIN20}
      - traefik.port=8888
      - traefik.docker.network=http_network
    environment:
      - DBDRIVER=pgsql
      - DBHOST=postgres
      - DBPORT=5432
      - DBPASS=${DATABASE_USER_PASSWORD}
    depends_on:
      - mailserver
      - postgres
      #- mariadb
    networks:
      - mail_network
      - http_network

  # Webmail (Optional)
  # https://github.com/hardware/rainloop
  # https://www.rainloop.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.port=8888
      - traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN2}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN3}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN4}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN5}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN6}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN7}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN8}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN9}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN10}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN11}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN12}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN13}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN14}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN15}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN16}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN17}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN18}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN19}
      #- traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN20}
      - traefik.docker.network=http_network
    volumes:
      - ${VOLUMES_ROOT_PATH}/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - postgres
      #- mariadb
    networks:
      - mail_network
      - http_network

  # Alternative webmail (Optional)
  # https://github.com/hardware/afterlogic-webmail-lite
  # https://afterlogic.org/webmail-lite
  # Configuration : https://github.com/hardware/mailserver/wiki/AfterLogic-Webmail-Lite-initial-configuration
  # afterlogic-webmail-lite:
  #   image: hardware/afterlogic-webmail-lite
  #   container_name: afterlogic-webmail-lite
  #   restart: ${RESTART_MODE}
  #   labels:
  #     - traefik.enable=true
  #     - traefik.port=8888
  #     - traefik.frontend.rule=Host:webmail.${MAILSERVER_DOMAIN}
  #     - traefik.docker.network=http_network
  #   volumes:
  #     - ${VOLUMES_ROOT_PATH}/afterlogic-webmail-lite:/afterlogic-webmail-lite/data
  #   depends_on:
  #     - mailserver
  #     - mariadb
  #   networks:
  #     - mail_network
  #     - http_network

  # Authoritative DNS server (Optional)
  # https://github.com/hardware/nsd-dnssec
  # https://www.nlnetlabs.nl/projects/nsd/
  # Configuration : https://github.com/hardware/mailserver/wiki/NSD-initial-configuration
  # nsd:
  #   image: hardware/nsd-dnssec
  #   container_name: nsd
  #   restart: ${RESTART_MODE}
  #   ports:
  #     - "53:53"
  #     - "53:53/udp"
  #   volumes:
  #     - ${VOLUMES_ROOT_PATH}/nsd/conf:/etc/nsd
  #     - ${VOLUMES_ROOT_PATH}/nsd/zones:/zones
  #     - ${VOLUMES_ROOT_PATH}/nsd/db:/var/db/nsd

  # Database
  # https://github.com/docker-library/postgres
  # https://postgresql.org/
  postgres:
    image: postgres:10.5-alpine
    container_name: postgres
    restart: ${RESTART_MODE}
    stop_signal: SIGINT                 # Fast Shutdown mode
    # Info : These variables are ignored when the volume already exists (if databases was created before).
    environment:
      - POSTGRES_DB=postfix
      - POSTGRES_USER=postfix
      - POSTGRES_PASSWORD=${DATABASE_USER_PASSWORD}
    volumes:
      - ${VOLUMES_ROOT_PATH}/pgsql/db:/var/lib/postgresql/data
    networks:
      - mail_network

  # # Database
  # # https://github.com/docker-library/mariadb
  # # https://mariadb.org/
  # mariadb:
  #   image: mariadb:10.2
  #   container_name: mariadb
  #   restart: ${RESTART_MODE}
  #   # Info : These variables are ignored when the volume already exists (if databases was created before).
  #   environment:
  #     - MYSQL_RANDOM_ROOT_PASSWORD=yes
  #     - MYSQL_DATABASE=postfix
  #     - MYSQL_USER=postfix
  #     - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
  #   volumes:
  #     - ${VOLUMES_ROOT_PATH}/mysql/db:/var/lib/mysql
  #   networks:
  #     - mail_network

  # Database
  # https://github.com/docker-library/redis
  # https://redis.io/
  redis:
    image: redis:4.0-alpine
    container_name: redis
    restart: ${RESTART_MODE}
    command: redis-server --appendonly yes
    volumes:
      - ${VOLUMES_ROOT_PATH}/redis/db:/data
    networks:
      - mail_network
